name: Continuous Integration

on:
  push:
    branches:
      - main  # Run workflow only when pushing to the main branch
  pull_request:  # Also run the workflow when a PR is raised

jobs:
  build-dotnet:
    name: Build and Test C#
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        run: dotnet test --no-build

  build-typescript:
    name: Build and Test TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TypeScript dependencies
        run: cd DotnetTemplate.Web && npm install && npm run build
      - name: Test with Jasmine
        run: cd DotnetTemplate.Web && npm t
      - name: Lint TypeScript
        working-directory: ./DotnetTemplate.Web
        run: npm run lint
